spring:
  datasource:
    url: jdbc:mysql://localhost:3308/authz?useSSL=false&serverTimezone=UTC&useLegacyDatetimeCode=false&allowPublicKeyRetrieval=true
    username: root
    password: toor
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
  jackson:
    default-property-inclusion: non_null # to exclude null in json serialization
    serialization:
      write-dates-as-timestamps: true # write milliseconds since epoch in the final json

server:
  port: 8080

security:
  jwt:
    token:
      secret-key: secret-key
      expire-length: 300000

logging:
  level:
    root: INFO
    org.hibernate.SQL: DEBUG
